- .travis.yml
- build/lint-commits.sh
- ex/app/components/guide/log/log.component.html
- ex/app/components/guide/log/log.component.ts
- ex/app/data/table/code.ts
- ex/app/data/table/table.component.html
- ex/app/data/table/table.component.ts
- ex/app/form/cascader/code.ts
- ex/app/form/form/code.ts
- ex/docs/cascader.json
- ex/docs/changelog.json
- ex/docs/table-column.json
- package-lock.json
- package.json
- src/cascader/cascader.ts
- src/date-picker/children/date-table.ts
- src/date-picker/picker.ts
- src/table/children/body.ts
- src/table/children/column.ts
- src/table/table.interface.ts
- src/table/table.ts
> feat(table): add render-html attr

- ex/app/components/footer/footer.component.html
- ex/app/components/header/header.component.html
- ex/docs/changelog.json
- package.json
- src/loading/loading.directive.ts
> build(pkg): v0.5.4

- ex/docs/changelog.json
- ex/docs/loading.json
- ex/docs/menu-item.json
- package-lock.json
- package.json
- src/menu/menu-item.ts
- src/switch/switch.ts
> fix(switch): solve switch model change with form

- ex/app/data/tree/code.ts
- ex/docs/changelog.json
- package-lock.json
- package.json
- src/tree/tree-props.ts
- src/tree/tree.ts
> fix(tree): fix standard init

- ex/app/data/tree/tree.component.html
- ex/docs/changelog.json
- ex/docs/tree.json
- package-lock.json
- package.json
- src/switch/switch.ts
- tsconfig.json
> refactor(compile): adjust target

- ex/docs/changelog.json
- package-lock.json
- package.json
- src/collapse/collapse-item.ts
- src/collapse/collapse.ts
> fix: solve binding miss

- ex/app/basic/container/code.ts
- ex/app/basic/container/container.component.html
- ex/app/basic/container/container.component.ts
- ex/docs/changelog.json
- ex/docs/container.json
- ex/docs/en-US/cascader.json
- ex/docs/en-US/changelog.json
- ex/docs/en-US/container.json
- ex/docs/en-US/loading.json
- ex/docs/en-US/menu-item.json
- ex/docs/en-US/table-column.json
- ex/docs/en-US/tree.json
- package-lock.json
- package.json
- src/container/children/aside.ts
- src/container/children/footer.ts
- src/container/children/header.ts
- src/container/children/main.ts
- src/container/container.directive.ts
- src/container/container.ts
- src/container/directives/aside.directive.ts
- src/container/directives/footer.directive.ts
- src/container/directives/header.directive.ts
- src/container/directives/index.ts
- src/container/directives/main.directive.ts
- src/container/module.ts
> feat(container): add container directive

- ex/app/basic/container/code.ts
> fix(container): fix example

- ex/docs/changelog.json
- ex/docs/input.json
- package-lock.json
- package.json
- src/input/input-props.ts
- src/input/input.ts
> fix(input): fix icon event in form namespace

- src/dropdown/dropdown.ts
> style(dropdown): remove log

- ex/docs/changelog.json
- ex/docs/en-US/changelog.json
- ex/docs/en-US/dropdown.json
- ex/docs/en-US/input.json
- package.json
- src/dropdown/dropdown.ts
- src/pagination/children/button.ts
- src/pagination/children/pager.ts
- src/pagination/pagination.ts
> fix(pagination): fix total watch

- ex/docs/changelog.json
- ex/docs/col.json
- package-lock.json
- package.json
- src/col/col.directive.ts
- src/radio/radio-group.ts
> fix: fix form patch

- src/table/children/header.ts
> fix(table): fix center style

- ex/docs/changelog.json
- package.json
- src/table/children/body.ts
- src/table/table.ts
> fix: fix table binding

- src/table/table.ts
fix(table): fix column sort issue when hidden column index undefined
Please refer below link to reproduce bug
[https://stackblitz.com/edit/angular-ymtsxj?file=app%2Fapp.component.html](https://stackblitz.com/edit/angular-ymtsxj?file=app%2Fapp.component.html)
fix column sort issue when hidden column index undefined
> fix(table): fix column sort issue when hidden column index undefined

- ex/docs/changelog.json
- package.json
- src/pagination/pagination.ts
> fix(pagination): fix model empty

- src/select/select.ts
> fix(select): fix select writable state

- src/message/message.animation.ts
- src/message/message.ts
> fix(message): fix message animation

- ex/docs/changelog.json
- package-lock.json
- package.json
> build: v0.6.6

- ex/docs/changelog.json
- package-lock.json
- package.json
- src/table/table.ts
> fix(table): fix table do-check when missing slot

- ex/app/form/select/code.ts
- ex/app/form/select/select.component.html
- ex/app/form/select/select.component.ts
- ex/docs/changelog.json
- ex/docs/select.json
- package-lock.json
- package.json
- src/select/option.ts
- src/select/select-props.ts
- src/select/select.ts
- src/tag/tag.ts
> feat(select): append multiple attr

- src/tree/tree-item.ts
> fix(tree): fix tree event

- ex/docs/changelog.json
- package-lock.json
- package.json
- src/select/select.ts
> build(pkg): v0.7.1

- ex/docs/changelog.json
- package-lock.json
- package.json
- src/select/select.ts
> build(pkg): v0.7.2

- ex/docs/changelog.json
- package-lock.json
- package.json
- src/select/select.ts
> fix(select): fix init value of multiple select

- ex/app/form/form/code.ts
- ex/app/form/form/form.component.ts
- ex/docs/changelog.json
- package-lock.json
- package.json
- src/select/option.ts
- src/select/select.ts
> fix(select): fix init in form group

- ex/app/others/collapse/code.ts
- ex/docs/collapse.json
- src/collapse/collapse-item.ts
- src/collapse/collapse.ts
> feat: collapse model tracking

- ex/docs/changelog.json
- package.json
- src/radio/radio-group.ts
- src/radio/radio.ts
> fix(radio): fix disabled attr in group mode

- src/pagination/pagination.ts
> fix(pagiantion): fix total init

- src/carousel/carousel.ts
> fix(carousel): fix model change

- src/upload/module.ts
> style(upload): remove http module

- ex/docs/changelog.json
- package.json
> build(pkg): v0.7.6

- src/radio/radio.ts
- src/select/select.ts
> fix(select): fix value track
